version: "3.7"

services:
  controller:
    image: agoat/routing-mesh-controller:latest
    deploy:
      mode: global
    labels:
      routing.mesh.controller: "true"
    networks:
      routingmesh:
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    volumes:
      - "config:/etc/nginx/conf.d:ro"
      - "challenges:/var/lib/letsencrypt:ro"
      - "certs:/etc/letsencrypt:ro"

  manager:
    image: agoat/routing-mesh-manager:latest
    deploy:
      mode: global
    environment:
      ROUTING_NETWORK: "routingmesh"
      LETSENCRYPT_EMAIL: "your@email.xyz"
    networks:
      internet:
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "config:/etc/nginx/conf.d"
      - "challenges:/var/lib/letsencrypt"
      - "certs:/etc/letsencrypt"

volumes:
  config:
  challenges:
  certs:
#    name: "letsencrypt-certs"

networks:
  routingmesh:
    attachable: true
    name: "routingmesh"
  internet:




# DEV

version: "3.7"

services:
  controller:
    image: agoat/routing-mesh-controller:1.3
    deploy:
      mode: global
    labels:
      routing.mesh.controller: "true"
    networks:
      routingmesh:
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    volumes:
      - "config:/etc/nginx/conf.d:ro"
      - "challenges:/var/lib/letsencrypt:ro"
      - "certs:/etc/letsencrypt:ro"

  manager:
    image: agoat/routing-mesh-manager:2.0.0
    #    command: sleep 200d
    deploy:
      mode: global
    #      placement:
    #        constraints: [node.role == manager]
    environment:
      ROUTING_NETWORK: "routingmesh"
      LETSENCRYPT_EMAIL: "mehh@agoat.xyz"
      DHPARAM_KEYSIZE: 2048
    networks:
      conn:
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "config:/etc/nginx/conf.d"
      - "challenges:/var/lib/letsencrypt"
      - "certs:/etc/letsencrypt"
      - "/var/www/.environment/routing/routing-mesh/build/routing-mesh-manager/2.0:/scripts"

volumes:
  config:
    driver_opts:
      type: "nfs"
      o: "addr=185.163.119.232,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14"
      device: ":/volumes/RoutingMesh_config"
  challenges:
    driver_opts:
      type: "nfs"
      o: "addr=185.163.119.232,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14"
      device: ":/volumes/RoutingMesh_challenges"
  certs:
    driver_opts:
      type: "nfs"
      o: "addr=185.163.119.232,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14"
      device: ":/volumes/RoutingMesh_certs"

networks:
  routingmesh:
    attachable: true
    name: "routingmesh"
  conn:
