version: "3.7"

services:
  controller:
    image: agoat/routing-mesh-controller:latest
    deploy:
      mode: global
    labels:
      routing.mesh.controller: "true"
    networks:
      controller:
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    volumes:
      - "config:/etc/nginx/conf.d:ro"
      - "challenges:/var/www/letsencrypt:ro"
      - "certs:/etc/letsencrypt:ro"

  manager:
    image: agoat/routing-mesh-manager:latest
    deploy:
      mode: global
    environment:
      ROUTING_NETWORK: "routingmesh"
      LETSENCRYPT_EMAIL: "your@email.xyz"
      NODE_ID: '{{.Node.ID}}'
    networks:
      manager:
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "config:/etc/nginx/conf.d"
      - "challenges:/var/www/letsencrypt"
      - "certs:/etc/letsencrypt"

volumes:
  config:
#    driver_opts:
#      type: "nfs"
#      o: "addr=<nfs-server-ip>,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14"
#      device: ":/<nfs-share-folder>"
  challenges:
#    driver_opts:
#      type: "nfs"
#      o: "addr=<nfs-server-ip>,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14"
#      device: ":/<nfs-share-folder>"
  certs:
#    driver_opts:
#      type: "nfs"
#      o: "addr=<nfs-server-ip>,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14"
#      device: ":/<nfs-share-folder>"

networks:
  controller:
    attachable: true
    name: "routingmesh"
  manager:
    name: "routingmesh_manager"
