version: "3.5"

services:
  controller:
    image: agoat/routing-mesh-controller:1.0
    deploy:
      mode: global
    labels:
      routing.mesh.controller: "true"
    networks:
      routingmesh:
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    volumes:
      - "config:/etc/nginx/conf.d:ro"
      - "challenges:/var/lib/letsencrypt:ro"
      - "certs:/etc/letsencrypt:ro"

  manager:
    image: agoat/routing-mesh-manager:1.1
    environment:
      ROUTING_NETWORK: "routingmesh"
      LETSENCRYPT_EMAIL: "your@email.xyz"
    networks:
      internet:
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "config:/etc/nginx/conf.d"
      - "challenges:/var/lib/letsencrypt"
      - "certs:/etc/letsencrypt"

volumes:
  config:
  challenges:
  certs:
    name: "letsencrypt-certs"

networks:
  routingmesh:
    external: true
#    attachable: true
#    name: "routingmesh"
  internet:
